title: goseoan blog
description: goseoan blog

url: https://goseoan.github.io
baseurl: ""

markdown: goseoan
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: goseoan
   facebook: goseoan
   email: goseoan@gmail.com

google_analytics: "UA-58263416-1"
